### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by braksator** [stpettersens/node-magic-number#1]
Thanks for the code but I'm unable to use this as a dependency because it simply doesn't work.  I had to hack this module quite a bit to make it work.

Here's the code now:

```
/*
 Magic number detection for Node.js
 Copyright 2015 Sam Saint-Pettersen

 Released under the MIT License.
 */
var fs = require('fs');
var path = require('path');

var MagicNumber = (function () {
    function MagicNumber() {
    }

    MagicNumber.loadFileTypes = function () {
        MagicNumber.mimes = new Array();
        MagicNumber.ids = new Array();
        var data = fs.readFileSync(path.resolve(__dirname, 'file.types'), 'utf8');

        var lines = data.toString().split('\n');
        for (var i = 0; i < lines.length; i++) {
            var mi = lines[i].split(':');
            if (mi[0] != '') {
                MagicNumber.mimes.push(mi[0]);
                MagicNumber.ids.push(mi[1]);
            }
        }
    };
    MagicNumber.detectFile = function (file) {
        MagicNumber.loadFileTypes();
        var type = 'unknown';
        var data = fs.readFileSync(file, 'binary');
        for (var i = 0; i < MagicNumber.ids.length; i++) {
            var file_mn = '';
            var compare_mn = MagicNumber.ids[i];
            for (var x = 0; x < compare_mn.length; x++) {
                file_mn += data[x];
            }
            if (file_mn == compare_mn) {
                type = MagicNumber.mimes[i];
                break;
            }
        }
        return type;
    };
    return MagicNumber;
})();
module.exports = MagicNumber;

```

- Removed the fileExistsSync() calls.  If files don't exist your module SHOULD shit itself, not just display a console.log message.

- 'file.types' read now looks for it in the correct directory, this required path module too.

- Removed toChar() function

- readFileSync() calls now pass the encoding parameter

in file.types I had to add more lines for jpeg:

```
image/jpeg:ÿØÿà
image/jpeg:ÿØÿÛ
image/jpeg:ÿØÿá
```

https://en.wikipedia.org/wiki/List_of_file_signatures

IMO it should also return false not 'unknown' for unhandled mimes, but that's just personal.

I guess I'd change some other things, but getting it working should be a priority :D

**Comment by braksator** [comment]
it just occurred to me that you may have intended file.types to be provided by the caller in their module, which is not a bad idea I guess.  But if someone wants to do that they can override loadFileTypes().

**Comment by stpettersens** [comment]
> it just occurred to me that you may have intended file.types to be provided by the caller in their module. [...] But if someone wants to do that they can override loadFileTypes().

The plan was that the module user defines the types they need to detect in a file.types file in their own project.  They can indeed override the loadFileTypes method too. 

> Removed the fileExistsSync() calls. If files don't exist your module SHOULD shit itself, not just display a console.log message.

By *shit itself*, I guess you mean throw an Exception. Fair point. I can modify the code to do so. 

Thank you for posting an issue. If you file a pull request with your changes, I'll happily merge those and add you to the contributors in package.json.
