### ISSUE TITLE
Cannot find module 'magic-number'

### ISSUE THREAD

**Issue by thom4parisot** [stpettersens/node-magic-number#5]
It seems that when the package is installed, the JavaScript files are missing:

```bash
$ npm i magic-number
$ ls -a node_modules/magic-number/
.                      LICENSE                file.exts              magic-number-0.1.5.tgz
..                     README.markdown        file.types             package.json
```

I guess they were not built from the TypeScript sources prior to the last release 🙂

**Comment by stpettersens** [comment]
I have probably made a mistake last time I updated it. Please give me a few days to look into it or feel free to find my mistake, fix and submit a PR.  I'm on a deadline with something else so I can't look at it for a while. Sorry about that. 

Thank you for submitting the issue though; helps me out.

**Comment by stpettersens** [comment]
* If it is was I suspect (that you elude to about building from TypeScript) then I suspect I forgot to build first when I published the new version; which I might be able to quickly fix this evening. In the meantime, please try `npm install magic-number@0.1.4`.

**Comment by stpettersens** [comment]
I have fixed this and published magic-number 0.1.6.
`npm install magic-number@0.1.6`

Thanks, @oncletom !

**Comment by thom4parisot** [comment]
Thanks @stpettersens 🙂  Glad it helped! Will try it out now.

All the best with your deadline.

**Comment by stpettersens** [comment]
Thank you. This error was pretty much what you said - an oversight in that I forgot to build the module first before packing it. Whoops.  =/
